src/meal/urls.py
from django.conf.urls import url

app_name = "meal"
urlpatterns = []

src/member/urls.py
from django.conf.urls import url
from django.utils.translation import ugettext_lazy as _
from django.utils.translation import string_concat

from member.views import (
    ClientWizard,
    ClientDetail,
    ClientList,
    SearchMembers,
    ClientOrderList,
    ClientInfoView,
    ClientPaymentView,
    ClientAllergiesView,
    DeleteRestriction,
    DeleteClientOption,
    DeleteIngredientToAvoid,
    DeleteComponentToAvoid,
    geolocateAddress,
    ClientStatusScheduler,
    ClientStatusSchedulerReschedule,
    ClientStatusView,
    ClientStatusSchedulerDeleteView,
    ClientUpdateBasicInformation,
    ClientUpdateAddressInformation,
    ClientUpdatePaymentInformation,
    ClientUpdateDietaryRestriction,
    ClientUpdateRelationshipsInformation,
    RouteListView,
    RouteDetailView,
    RouteEditView,
    DeliveryHistoryDetailView,
    get_minimised_euclidean_distances_route_sequence,
)

from member.forms import (
    ClientBasicInformation, ClientAddressInformation,
    ClientPaymentInformation, ClientRestrictionsInformation
)
from member.formsets import CreateRelationshipFormset

from note.views import ClientNoteList, ClientNoteListAdd

app_name = "member"

member_forms = ({
    'name':        'basic_information',
    'step_url':    _('basic_information'),
    'create_form': ClientBasicInformation,
    'update_form': ClientUpdateBasicInformation
}, {
    'name':        'address_information',
    'step_url':    _('address_information'),
    'create_form': ClientAddressInformation,
    'update_form': ClientUpdateAddressInformation
}, {
    'name':        'relationships',
    'step_url':    _('relationships'),
    'create_form': CreateRelationshipFormset,
    'update_form': ClientUpdateRelationshipsInformation
}, {
    'name':        'payment_information',
    'step_url':    _('payment_information'),
    'create_form': ClientPaymentInformation,
    'update_form': ClientUpdatePaymentInformation,
}, {
    'name':        'dietary_restriction',
    'step_url':    _('dietary_restriction'),
    'create_form': ClientRestrictionsInformation,
    'update_form': ClientUpdateDietaryRestriction,
})

member_wizard = ClientWizard.as_view(
    list(map(lambda d: (d['name'], d['create_form']), member_forms)),
    i18n_url_names=list(map(
        lambda d: (d['name'], d['step_url']), member_forms
    )),
    url_name='member:member_step'
)


urlpatterns = [
    url(_(r'^create/$'), member_wizard, name='member_step'),
    url(_(r'^create/(?P<step>.+)/$'), member_wizard,
        name='member_step'),
    url(_(r'^list/$'), ClientList.as_view(), name='list'),
    url(_(r'^search/$'), SearchMembers.as_view(), name='search'),
    url(_(r'^view/(?P<pk>\d+)/$'), ClientDetail.as_view(), name='view'),
    url(_(r'^view/(?P<pk>\d+)/orders$'),
        ClientOrderList.as_view(), name='list_orders'),
    url(_(r'^view/(?P<pk>\d+)/information$'),
        ClientInfoView.as_view(), name='client_information'),
    url(_(r'^view/(?P<pk>\d+)/billing$'),
        ClientPaymentView.as_view(), name='client_payment'),
    url(_(r'^view/(?P<pk>\d+)/preferences$'),
        ClientAllergiesView.as_view(), name='client_allergies'),
    url(_(r'^view/(?P<pk>\d+)/notes$'),
        ClientNoteList.as_view(), name='client_notes'),
    url(_(r'^view/(?P<pk>\d+)/notes/add$'),
        ClientNoteListAdd.as_view(), name='client_notes_add'),
    url(_(r'^geolocateAddress/$'), geolocateAddress, name='geolocateAddress'),
    url(_(r'^view/(?P<pk>\d+)/status$'),
        ClientStatusView.as_view(), name='client_status'),
    url(_(r'^client/(?P<pk>\d+)/status/scheduler$'),
        ClientStatusScheduler.as_view(), name='clientStatusScheduler'),
    url(_(r'^client/(?P<pk>\d+)/status/scheduler/reschedule/'
          r'(?P<scheduled_status_1_pk>\d+)'
          r',(?P<scheduled_status_2_pk>\d+)?'
          r'/$'),
        ClientStatusSchedulerReschedule.as_view(),
        name='clientStatusSchedulerReschedule'),
    url(
        r'^status/(?P<pk>\d+)/delete$',
        ClientStatusSchedulerDeleteView.as_view(),
        name='delete_status'
    ),
    url(_(r'^restriction/(?P<pk>\d+)/delete/$'),
        DeleteRestriction.as_view(), name='restriction_delete'),
    url(_(r'^client_option/(?P<pk>\d+)/delete/$'),
        DeleteClientOption.as_view(), name='client_option_delete'),
    url(_(r'^ingredient_to_avoid/(?P<pk>\d+)/delete/$'),
        DeleteIngredientToAvoid.as_view(), name='ingredient_to_avoid_delete'),
    url(_(r'^component_to_avoid/(?P<pk>\d+)/delete/$'),
        DeleteComponentToAvoid.as_view(), name='component_to_avoid_delete'),

    url(_(r'^routes/$'), RouteListView.as_view(), name='route_list'),
    url(_(r'^route/(?P<pk>\d+)/$'),
        RouteDetailView.as_view(), name='route_detail'),
    url(_(r'^route/(?P<pk>\d+)/edit/$'),
        RouteEditView.as_view(), name='route_edit'),
    url(_(r'^route/(?P<pk>\d+)/optimised_sequence/$'),
        get_minimised_euclidean_distances_route_sequence,
        name='route_get_optimised_sequence'),
    url(_(r'^route/(?P<route_pk>\d+)/(?P<date>\d{4}-\d{2}-\d{2})/$'),
        DeliveryHistoryDetailView.as_view(), name='delivery_history_detail'),
]

# Handle client update forms URL
for d in member_forms:
    urlpatterns.append(
        url(string_concat(_(r'^(?P<pk>\d+)/update/'), d['step_url'], '/$'),
            d['update_form'].as_view(),
            name='member_update_' + d['name'])
    )

src/note/urls.py
from django.conf.urls import url
from django.utils.translation import ugettext_lazy as _

from note.views import NoteList, NoteAdd, NoteBatchToggle

from note.views import mark_as_read, mark_as_unread

app_name = "note"

urlpatterns = [
    url(_(r'^$'), NoteList.as_view(), name='note_list'),
    url(_(r'^read/(?P<id>\d+)/$'),
        mark_as_read, name='read'),
    url(_(r'^unread/(?P<id>\d+)/$'),
        mark_as_unread, name='unread'),
    url(_(r'^add/$'), NoteAdd.as_view(), name='note_add'),
    url(_(r'^batch_toggle/$'),
        NoteBatchToggle.as_view(), name='batch_toggle'),
]

src/sous_chef/urls.py
from django.conf.urls import include, url
from django.contrib import admin


from page.views import HomeView
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import ugettext_lazy as _

urlpatterns = i18n_patterns(
    url(
        _(r'^admin/'),
        admin.site.urls
    ),
    url(
        _(r'^meal/'),
        include('meal.urls', namespace="meal")
    ),
    url(
        _(r'^member/'),
        include('member.urls', namespace="member")
    ),
    url(
        _(r'^notification/'),
        include('notification.urls', namespace="notification")
    ),
    url(
        _(r'^order/'),
        include('order.urls', namespace="order")
    ),
    url(
        r'^p/',
        include('page.urls', namespace="page")
    ),
    url(r'^$', HomeView.as_view(), name='home'),
    url(
        _(r'^delivery/'),
        include('delivery.urls', namespace="delivery")
    ),
    url(
        _(r'^note/'),
        include('note.urls', namespace="note")
    ),
    url(
        _(r'^billing/'),
        include('billing.urls', namespace="billing")
    ),
    url(
        _(r'^avatar/'),
        include('avatar.urls')
        ),
    prefix_default_language=False
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/note/models.py
from django.db import models
from django.db.models import Q
from django_filters import ChoiceFilter, DateFilter, FilterSet, CharFilter
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import User
from django.utils import timezone


# Create your models here.

class NoteManager(models.Manager):
    pass


class UnreadNoteManager(NoteManager):

    def get_queryset(self):

        return super(UnreadNoteManager, self).get_queryset().filter(
            is_read=0
        )


class NotePriority(models.Model):
    name = models.CharField(max_length=150, verbose_name=_('Name'))

    class Meta:
        verbose_name_plural = _('Note priorities')
        ordering = ('name',)

    def __str__(self):
        return u"%s" % self.name


class NoteCategory(models.Model):
    name = models.CharField(max_length=150, verbose_name=_('Name'))

    class Meta:
        verbose_name_plural = _('Note categories')
        ordering = ('name',)

    def __str__(self):
        return u"%s" % self.name


class Note(models.Model):

    class Meta:
        verbose_name_plural = _('Notes')
        ordering = ('-date', 'note')

    note = models.TextField(
        verbose_name=_('Note')
    )

    author = models.ForeignKey(
        User,
        verbose_name=_('Author'),
        null=True,
        on_delete=models.SET_NULL
    )

    date = models.DateTimeField(
        verbose_name=_('Date'),
        default=timezone.now,
    )

    is_read = models.BooleanField(
        verbose_name=_('Is read'),
        default=False
    )

    client = models.ForeignKey(
        'member.Client',
        verbose_name=_('Client'),
        related_name='client_notes',
        on_delete=models.CASCADE
    )

    priority = models.ForeignKey(
        NotePriority,
        verbose_name=_('Priority'),
        related_name="notes",
        null=True,
        on_delete=models.SET_NULL
    )

    category = models.ForeignKey(
        NoteCategory,
        verbose_name=_('Category'),
        related_name="notes",
        null=True,
        on_delete=models.SET_NULL
    )

    objects = NoteManager()

    unread = UnreadNoteManager()

    def __str__(self):
        return self.note

    def mark_as_read(self):
        """Mark a note as read."""
        if not self.is_read:
            self.is_read = True
            self.save()

    def mark_as_unread(self):
        """Mark a note as nread."""
        if self.is_read:
            self.is_read = False
            self.save()


class NoteFilter(FilterSet):

    IS_READ_CHOICES = (
        ('', 'All'),
        ('1', 'Yes'),
        ('0', 'No'),
    )

    NOTE_STATUS_UNREAD = IS_READ_CHOICES[2][0]

    is_read = ChoiceFilter(
        choices=IS_READ_CHOICES,
    )

    name = CharFilter(
        method='filter_search',
        label=_('Search by name')
    )

    date = DateFilter(lookup_expr='contains')

    class Meta:
        model = Note
        fields = ['priority', 'is_read', 'date', 'category', ]

    def filter_search(self, queryset, field_name, value):
        if not value:
            return queryset

        names = value.split(' ')

        name_contains = Q()

        for name in names:
            firstname_contains = Q(
                client__member__firstname__icontains=name
            )

            name_contains |= firstname_contains

            lastname_contains = Q(
                client__member__lastname__icontains=name
            )
            name_contains |= lastname_contains

        return queryset.filter(
            name_contains
        )

src/note/forms.py
from django import forms
from member.models import Client
from note.models import Note


class NoteForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(NoteForm, self).__init__(*args, **kwargs)
        self.fields['client'].queryset = Client.objects.all().select_related(
            'member'
        ).only(
            'member__firstname',
            'member__lastname'
        )

    class Meta:
        model = Note
        fields = ['note', 'client', 'priority', 'category']

        widgets = {
            'note': forms.Textarea(attrs={'rows': 5}),
            'client': forms.Select(
                attrs={'class': 'ui search dropdown'}
            ),
            'priority': forms.Select(
                attrs={'class': 'ui dropdown'}
            ),
            'category': forms.Select(
                attrs={'class': 'ui dropdown'}
            ),
        }

src/note/views.py
from django.shortcuts import get_object_or_404
from django.views import generic, View
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.db.models import Case, When
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _
from django.http import HttpResponseRedirect

from note.models import Note, NoteFilter
from note.forms import NoteForm
from member.models import Client


# Create your views here.

class NoteList(
        LoginRequiredMixin, PermissionRequiredMixin, generic.ListView):
    # Display the list of notes
    context_object_name = 'notes'
    model = Note
    paginate_by = 20
    permission_required = 'sous_chef.read'
    template_name = 'notes_list.html'

    def get_queryset(self):
        uf = NoteFilter(self.request.GET)
        return uf.qs.select_related(
            'client__member'
        )

        # The queryset must be client

    def get_context_data(self, **kwargs):
        uf = NoteFilter(self.request.GET, queryset=self.get_queryset())

        context = super(NoteList, self).get_context_data(**kwargs)

        # Here you add some variable of context to display on template
        context['filter'] = uf
        text = ''
        count = 0
        for getVariable in self.request.GET:
            if getVariable == "page":
                continue
            for getValue in self.request.GET.getlist(getVariable):
                if count == 0:
                    text += "?" + getVariable + "=" + getValue
                else:
                    text += "&" + getVariable + "=" + getValue
                count += 1

        text = text + "?" if count == 0 else text + "&"
        context['get'] = text

        return context


class ClientNoteList(
        LoginRequiredMixin, PermissionRequiredMixin, generic.ListView):
    # Display detail of one client
    context_object_name = 'notes'
    model = Note
    permission_required = 'sous_chef.read'
    template_name = 'notes_client_list.html'

    def get_queryset(self):
        queryset = NoteFilter(
            self.request.GET,
            queryset=Note.objects.filter(
                client__id=self.kwargs['pk'])).qs
        return queryset

    def get_context_data(self, **kwargs):
        context = super(ClientNoteList, self).get_context_data(**kwargs)
        context['active_tab'] = 'notes'
        context['client_status'] = Client.CLIENT_STATUS
        context['client'] = get_object_or_404(Client, id=self.kwargs['pk'])
        context['filter'] = NoteFilter(
            self.request.GET, queryset=Note.objects.filter(
                client__id=self.kwargs['pk']))

        return context


class NoteAdd(LoginRequiredMixin, PermissionRequiredMixin, generic.CreateView):
    form_class = NoteForm
    model = Note
    permission_required = 'sous_chef.edit'
    template_name = 'notes_add.html'

    def form_valid(self, form):
        form.instance.author = self.request.user
        response = super(NoteAdd, self).form_valid(form)
        messages.add_message(
            self.request, messages.SUCCESS,
            _("The note has been created.")
        )
        return response

    def get_success_url(self):
        return reverse('note:note_list')


class ClientNoteListAdd(NoteAdd):
    """
    Reuses things from note.
    """
    def get_context_data(self, **kwargs):
        context = super(ClientNoteListAdd, self).get_context_data(**kwargs)
        context['client'] = get_object_or_404(Client, id=self.kwargs['pk'])
        return context

    def get_success_url(self):
        return reverse('member:client_notes', kwargs={'pk': self.kwargs['pk']})


@login_required
def mark_as_read(request, id):
    note = get_object_or_404(Note, pk=id)
    note.mark_as_read()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


@login_required
def mark_as_unread(request, id):
    note = get_object_or_404(Note, pk=id)
    note.mark_as_unread()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


class NoteBatchToggle(
        LoginRequiredMixin, PermissionRequiredMixin, View
):
    permission_required = 'sous_chef.read'

    def post(self, request, *args, **kwargs):
        ids = request.POST.getlist('note')
        count = Note.objects.filter(id__in=ids).update(is_read=Case(
            When(is_read=True, then=False),
            When(is_read=False, then=True)
        ))
        messages.add_message(
            self.request, messages.SUCCESS,
            _("%(count)s note(s) have been updated.") % {'count': count}
        )
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

src/note/templates/notes_add.html
{% extends "base.html" %}
<!-- Load internationalisation utils-->
{% load i18n %}


{% block content %}

<div class="ui secondary pointing fluid menu">
  <h1 class="ui header">
    {% block title %}
      {% if not client %}
        {% trans "Add a Note" %}
      {% else %}
        {% blocktrans trimmed with firstname=client.member.firstname|title lastname=client.member.lastname|title%}
         Add a Note for {{firstname}} {{lastname}}
        {% endblocktrans %}
      {% endif %}
    {% endblock %}
  </h1>

  <div class="right menu">

  </div>
</div>

<form action="" method="post" class="content ui form {% if form.errors %}error{% endif %}" novalidate>
  {% csrf_token %}
  {% if not client %}
  <div class="field {% if form.client.errors %}error{% endif %}">
      <label>{{ form.client.label }}</label>
      {{ form.client }}

      {% if form.client.errors %}
      <div class="ui error message">
        {{ form.client.errors }}
      </div>
      {% endif %}
  </div>
  {% else %}
  <input type="hidden" name="client" value="{{client.pk}}">
  {% endif %}

  <div class="field {% if form.note.errors %}error{% endif %}">
    <label>{{ form.note.label }}</label>
    {{ form.note }}

    {% if form.note.errors %}
    <div class="ui error message">
      {{ form.note.errors }}
    </div>
    {% endif %}
  </div>

  <div class="field {% if form.priority.errors %}error{% endif %}">
    <label>{{ form.priority.label }}</label>
    {{ form.priority }}

    {% if form.priority.errors %}
    <div class="ui error message">
      {{ form.priority.errors }}
    </div>
    {% endif %}
  </div>

  <div class="field {% if form.category.errors %}error{% endif %}">
    <label>{{ form.category.label }}</label>
    {{ form.category }}

    {% if form.category.errors %}
    <div class="ui error message">
      {{ form.category.errors }}
    </div>
    {% endif %}
  </div>

  <div class="ui row">
    <button class="ui primary button" type="submit">{% trans "Create" %}</button>
    <a class="ui button" href="{% if not client %}{% url 'note:note_list' %}{% else %}{% url 'member:client_notes' client.pk %}{% endif %}">{% trans "Cancel" %}</a>
  </div>
</form>

{% endblock %}

src/note/templates/notes_client_list.html
{% extends "client/base.html" %}
<!-- Load internationalisation utils-->
{% load i18n %}
{% load admin_urls %}
{% load rules %}

{% block title %}

  {{client}} - {% trans "Information" %}

{% endblock %}

{% block subcontent %}
{% has_perm 'sous_chef.edit' request.user as can_edit_data %}

<div class="ui segment">
    <h2 class="ui header">
        <div class="content">
            {% trans 'Staff Notes' %}
            <div class="sub header">
                {% trans "Notes added to" %} {{client}}'{% trans "s file" %}.
            </div>
        </div>
    </h2>
    <div class="ui divider"></div>


    <form action="" method="get" class="ui form">

        <div class="inline fields">

            <div class="field">
                <label>{% trans "Priority" %}</label>
                <div class="field">
                    {{ filter.form.priority }}
                </div>
            </div>

            <div class="field">
                <label>{% trans "Is read" %}</label>
                <div class="field">
                    {{ filter.form.is_read }}
                </div>
            </div>

            <input id="id_display" name="display" type="text" value="{{display}}" style="display:none">
        </div>
        <div class="field">
            <a href="{{ request.path }}?display={{ display }}" class="ui button">{% trans "Reset" %}</a>
            <button class="ui yellow button" type="submit">{% trans "Search" %}</button>
            {% if can_edit_data %}
            <a href="{% url 'member:client_notes_add' client.pk %}" class="ui button">
              <i class="add icon"></i>{% trans "New Note" %}
            </a>
            {% endif %}
        </div>
    </form>



    <table class="ui very basic compact table">
      <tbody>
        {% for note in notes %}
        <tr {% if not note.is_read %} class="{% if note.priority == 'urgent' %}warning{% else %}warning{% endif %}" {% endif %}>
          <td class="center aligned">
            {% if note.priority == 'urgent' %}
            <i class="warning sign middle aligned icon" title="{% trans 'Urgent' %}"></i>
            {% else %}
            {{note.category}}
            {% endif %}
          </td>
          <td style="width:100%;{% if not note.is_read %}font-weight:bold!important{% endif %}">
            <a class="header">{{note.date}}</a>
            <div class="description">
              {{ note.note }}
            </div>
            <div class="author">
                <small>{% trans 'Created by' %} {{note.author}}</small>
            </div>
          </td>
          <td class="right aligned" style="white-space:nowrap">
            {% if note.is_read %}
            <button class="ui tiny basic button" data-note-id="{{note.id}}" data-batch-commit-btn="#batch-commit-btn">
              {% trans 'Mark as unread' %}
            </button>
            {% else %}
            <button class="ui tiny basic yellow button" data-note-id="{{note.id}}" data-batch-commit-btn="#batch-commit-btn">
              {% trans 'Mark as read' %}
            </button>
            {% endif %}
          </td>
        </tr>
        {% endfor %}
      </tbody>
      <tfoot>
        <tr>
          <th colspan="3">
            <form action="{% url 'note:batch_toggle' %}" method="post" style="float:right">
              {% csrf_token %}
              {% for note in notes %}
              {% if not note.is_read %}
              <input type="hidden" name="note" value="{{ note.id }}">
              {% endif %}
              {% endfor %}
              <button class="ui button" type="submit">
                {% trans 'Mark all as read' %}
              </button>
            </form>

            <form action="{% url 'note:batch_toggle' %}" method="post" style="float:right;margin-right:0.5em">
              {% csrf_token %}
              <button type="submit" class="ui yellow button" style="display:none" id="batch-commit-btn">{% trans 'Commit selected changes' %}</button>
            </form>

          </th>
        </tr>
      </tfoot>
    </table>
</div>

{% endblock %}

src/note/templates/notes_list.html
{% extends "base.html" %}
<!-- Load internationalisation utils-->
{% load i18n %}
{% load rules %}
{% load sous_chef_extras %}

{% block title %}{% trans "Staff Notes" %}{% endblock %}

{% block content %}
{% has_perm 'sous_chef.edit' request.user as can_edit_data %}

<div class="ui secondary pointing fluid menu">
    <h1 class="ui header">{% trans "Staff Notes" %}</h1>

    <div class="right menu">

    </div>
</div>




<div class="ui padded basic segment">
    {% if can_edit_data %}
    <a href="{% url 'note:note_add' %}" class="ui labeled icon right basic big button">
        <i class="add icon"></i>{% trans 'New note' %}
    </a>
    <div class="ui horizontal divider">
        {% trans 'Or' %}
    </div>
    {% endif %}


    <div class="ui row">
      <form action="" method="get" class="ui form">

        <div class="inline fields">
          <div class="field">
            <label>{% trans "Name" %}</label>
            <div class="field">
              <div class="ui large left icon input">
                <i class="users icon"></i>
                {{ filter.form.name }}
              </div>
            </div>
          </div>
          <div class="field">
            <label>{% trans "Priority" %}</label>
            <div class="field">
              {{ filter.form.priority|alter_field_class:'ui dropdown' }}
            </div>
          </div>
          <div class="field">
            <label>{% trans "Category" %}</label>
            <div class="field">
              {{ filter.form.category|alter_field_class:'ui dropdown' }}
            </div>
          </div>
      </div>
      <div class="inline fields">
          <div class="field">
            <label>{% trans "Is read" %}</label>
            <div class="field">
              {{ filter.form.is_read|alter_field_class:'ui dropdown' }}
            </div>
          </div>
          <div class="field">
              <label>{% trans 'Date' %}</label>
              <div class="field">
                  <div class="ui calendar" id="note_date">
                      <div class="ui input left icon">
                            <i class="calendar icon"></i>
                            {{ filter.form.date }}
                      </div>
                  </div>
              </div>
          </div>
        </div>
        <div class="field">
          <a href="{{ request.path }}?display={{ display }}" class="ui button">{% trans "Reset" %}</a>
          <button class="ui yellow button" type="submit">{% trans "Search" %}</button>
        </div>
      </form>
    </div>
    <table class="ui basic compact table">
      <tbody>
        {% for note in notes %}
        <tr {% if not note.is_read %} class="{% if note.priority == 'urgent' %}warning{% else %}warning{% endif %}" {% endif %}>
          <td class="center aligned">
            {% if note.priority == "Urgent" %}
              {{note.priority}}
            <i class="warning sign middle aligned icon" title="{% trans 'Urgent' %}"></i>
            {% else %}
            <small>{{note.category}}</small>
            {% endif %}
          </td>
          <td style="width:100%;{% if not note.is_read %}font-weight:bold!important{% endif %}">
            <a class="header" href="{% url 'member:client_information' pk=note.client.id %}">{{note.client}}</a>
            <div class="description">
              {{ note.note }}
            </div>
            <div class="description">
              <div class="date">
                <small>{{note.date}} {% trans 'created by' %} {{note.author}}</small>
              </div>
            </div>
          </td>
          <td class="right aligned" style="white-space:nowrap">
            {% if note.is_read %}
            <button class="ui tiny basic button" data-note-id="{{note.id}}" data-batch-commit-btn="#batch-commit-btn">
              {% trans 'Mark as unread' %}
            </button>
            {% else %}
            <button class="ui tiny basic yellow button" data-note-id="{{note.id}}" data-batch-commit-btn="#batch-commit-btn">
              {% trans 'Mark as read' %}
            </button>
            {% endif %}
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>


    <div class="ui row">
      {% if is_paginated %}
      <div class="ui pagination menu" style="margin: 2em auto">
        {% if page_obj.has_previous %}
        <a class="icon item"
           href="{{ request.path }}{{ get }}page={{ page_obj.previous_page_number }}">
            <i class="left arrow icon"></i>
        </a>
        {% endif %}
        <a class="active item">
          {{ page_obj.number }} {% trans "of" %} {{ page_obj.paginator.num_pages }}
        </a>
        {% if page_obj.has_next %}
        <a class="icon item"
           href="{{ request.path }}{{ get }}page={{ page_obj.next_page_number }}">
            <i class="right arrow icon"></i>
        </a>
        {% endif %}
      </div>
      {% endif %}


      <form action="{% url 'note:batch_toggle' %}" method="post" style="float:right;margin-right:0.5em">
        {% csrf_token %}
        {% for note in notes %}
          {% if not note.is_read %}
          <input type="hidden" name="note" value="{{ note.id }}">
          {% endif %}
        {% endfor %}
        <button class="ui button" style="margin: 2em auto" type="submit">
          {% trans 'Mark all as read' %}
        </button>
      </form>

      <form action="{% url 'note:batch_toggle' %}" method="post" style="float:right;margin-right:0.5em">
        {% csrf_token %}
        <button type="submit" class="ui yellow button" style="margin: 2em auto; display:none" id="batch-commit-btn">{% trans 'Commit selected changes' %}</button>
      </form>
    </div>
</div>
{% endblock %}