src/billing/urls.py
from django.conf.urls import url
from billing.views import (
    BillingList, BillingCreate, BillingDelete,
    BillingSummaryView, BillingOrdersView, BillingAdd
)
from django.utils.translation import ugettext_lazy as _

app_name = "billing"

urlpatterns = [
    url(_(r'^list/$'), BillingList.as_view(), name="list"),
    url(_(r'^create/$'), BillingCreate.as_view(), name="create"),
    url(_(r'^add/$'), BillingAdd.as_view(), name="add"),
    url(_(r'^view/(?P<pk>\d+)/$'),
        BillingSummaryView.as_view(), name="view"),
    url(_(r'^view/(?P<pk>\d+)/orders/$'),
        BillingOrdersView.as_view(), name="view_orders"),
    url(_(r'^delete/(?P<pk>\d+)/$'), BillingDelete.as_view(), name='delete'),
]

src/meal/urls.py
from django.conf.urls import url

app_name = "meal"
urlpatterns = []

src/member/urls.py
from django.conf.urls import url
from django.utils.translation import ugettext_lazy as _
from django.utils.translation import string_concat

from member.views import (
    ClientWizard,
    ClientDetail,
    ClientList,
    SearchMembers,
    ClientOrderList,
    ClientInfoView,
    ClientPaymentView,
    ClientAllergiesView,
    DeleteRestriction,
    DeleteClientOption,
    DeleteIngredientToAvoid,
    DeleteComponentToAvoid,
    geolocateAddress,
    ClientStatusScheduler,
    ClientStatusSchedulerReschedule,
    ClientStatusView,
    ClientStatusSchedulerDeleteView,
    ClientUpdateBasicInformation,
    ClientUpdateAddressInformation,
    ClientUpdatePaymentInformation,
    ClientUpdateDietaryRestriction,
    ClientUpdateRelationshipsInformation,
    RouteListView,
    RouteDetailView,
    RouteEditView,
    DeliveryHistoryDetailView,
    get_minimised_euclidean_distances_route_sequence,
)

from member.forms import (
    ClientBasicInformation, ClientAddressInformation,
    ClientPaymentInformation, ClientRestrictionsInformation
)
from member.formsets import CreateRelationshipFormset

from note.views import ClientNoteList, ClientNoteListAdd

app_name = "member"

member_forms = ({
    'name':        'basic_information',
    'step_url':    _('basic_information'),
    'create_form': ClientBasicInformation,
    'update_form': ClientUpdateBasicInformation
}, {
    'name':        'address_information',
    'step_url':    _('address_information'),
    'create_form': ClientAddressInformation,
    'update_form': ClientUpdateAddressInformation
}, {
    'name':        'relationships',
    'step_url':    _('relationships'),
    'create_form': CreateRelationshipFormset,
    'update_form': ClientUpdateRelationshipsInformation
}, {
    'name':        'payment_information',
    'step_url':    _('payment_information'),
    'create_form': ClientPaymentInformation,
    'update_form': ClientUpdatePaymentInformation,
}, {
    'name':        'dietary_restriction',
    'step_url':    _('dietary_restriction'),
    'create_form': ClientRestrictionsInformation,
    'update_form': ClientUpdateDietaryRestriction,
})

member_wizard = ClientWizard.as_view(
    list(map(lambda d: (d['name'], d['create_form']), member_forms)),
    i18n_url_names=list(map(
        lambda d: (d['name'], d['step_url']), member_forms
    )),
    url_name='member:member_step'
)


urlpatterns = [
    url(_(r'^create/$'), member_wizard, name='member_step'),
    url(_(r'^create/(?P<step>.+)/$'), member_wizard,
        name='member_step'),
    url(_(r'^list/$'), ClientList.as_view(), name='list'),
    url(_(r'^search/$'), SearchMembers.as_view(), name='search'),
    url(_(r'^view/(?P<pk>\d+)/$'), ClientDetail.as_view(), name='view'),
    url(_(r'^view/(?P<pk>\d+)/orders$'),
        ClientOrderList.as_view(), name='list_orders'),
    url(_(r'^view/(?P<pk>\d+)/information$'),
        ClientInfoView.as_view(), name='client_information'),
    url(_(r'^view/(?P<pk>\d+)/billing$'),
        ClientPaymentView.as_view(), name='client_payment'),
    url(_(r'^view/(?P<pk>\d+)/preferences$'),
        ClientAllergiesView.as_view(), name='client_allergies'),
    url(_(r'^view/(?P<pk>\d+)/notes$'),
        ClientNoteList.as_view(), name='client_notes'),
    url(_(r'^view/(?P<pk>\d+)/notes/add$'),
        ClientNoteListAdd.as_view(), name='client_notes_add'),
    url(_(r'^geolocateAddress/$'), geolocateAddress, name='geolocateAddress'),
    url(_(r'^view/(?P<pk>\d+)/status$'),
        ClientStatusView.as_view(), name='client_status'),
    url(_(r'^client/(?P<pk>\d+)/status/scheduler$'),
        ClientStatusScheduler.as_view(), name='clientStatusScheduler'),
    url(_(r'^client/(?P<pk>\d+)/status/scheduler/reschedule/'
          r'(?P<scheduled_status_1_pk>\d+)'
          r',(?P<scheduled_status_2_pk>\d+)?'
          r'/$'),
        ClientStatusSchedulerReschedule.as_view(),
        name='clientStatusSchedulerReschedule'),
    url(
        r'^status/(?P<pk>\d+)/delete$',
        ClientStatusSchedulerDeleteView.as_view(),
        name='delete_status'
    ),
    url(_(r'^restriction/(?P<pk>\d+)/delete/$'),
        DeleteRestriction.as_view(), name='restriction_delete'),
    url(_(r'^client_option/(?P<pk>\d+)/delete/$'),
        DeleteClientOption.as_view(), name='client_option_delete'),
    url(_(r'^ingredient_to_avoid/(?P<pk>\d+)/delete/$'),
        DeleteIngredientToAvoid.as_view(), name='ingredient_to_avoid_delete'),
    url(_(r'^component_to_avoid/(?P<pk>\d+)/delete/$'),
        DeleteComponentToAvoid.as_view(), name='component_to_avoid_delete'),

    url(_(r'^routes/$'), RouteListView.as_view(), name='route_list'),
    url(_(r'^route/(?P<pk>\d+)/$'),
        RouteDetailView.as_view(), name='route_detail'),
    url(_(r'^route/(?P<pk>\d+)/edit/$'),
        RouteEditView.as_view(), name='route_edit'),
    url(_(r'^route/(?P<pk>\d+)/optimised_sequence/$'),
        get_minimised_euclidean_distances_route_sequence,
        name='route_get_optimised_sequence'),
    url(_(r'^route/(?P<route_pk>\d+)/(?P<date>\d{4}-\d{2}-\d{2})/$'),
        DeliveryHistoryDetailView.as_view(), name='delivery_history_detail'),
]

# Handle client update forms URL
for d in member_forms:
    urlpatterns.append(
        url(string_concat(_(r'^(?P<pk>\d+)/update/'), d['step_url'], '/$'),
            d['update_form'].as_view(),
            name='member_update_' + d['name'])
    )

src/sous_chef/urls.py
from django.conf.urls import include, url
from django.contrib import admin


from page.views import HomeView
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import ugettext_lazy as _

urlpatterns = i18n_patterns(
    url(
        _(r'^admin/'),
        admin.site.urls
    ),
    url(
        _(r'^meal/'),
        include('meal.urls', namespace="meal")
    ),
    url(
        _(r'^member/'),
        include('member.urls', namespace="member")
    ),
    url(
        _(r'^notification/'),
        include('notification.urls', namespace="notification")
    ),
    url(
        _(r'^order/'),
        include('order.urls', namespace="order")
    ),
    url(
        r'^p/',
        include('page.urls', namespace="page")
    ),
    url(r'^$', HomeView.as_view(), name='home'),
    url(
        _(r'^delivery/'),
        include('delivery.urls', namespace="delivery")
    ),
    url(
        _(r'^note/'),
        include('note.urls', namespace="note")
    ),
    url(
        _(r'^billing/'),
        include('billing.urls', namespace="billing")
    ),
    url(
        _(r'^avatar/'),
        include('avatar.urls')
        ),
    prefix_default_language=False
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/billing/views.py
import copy
import collections

from django.db.models import Q, Count, Prefetch
from django.views import generic
from django.utils.translation import string_concat
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.contrib import messages

from billing.models import (
    Billing, BillingFilter
)
from order.models import DeliveredOrdersByMonth
from django.urls import reverse_lazy
from order.models import Order, Order_item
from django.http import HttpResponseRedirect
from member.models import Client


class BillingList(
        LoginRequiredMixin, PermissionRequiredMixin, generic.ListView):
    # Display the billing list
    context_object_name = "billings"
    model = Billing
    permission_required = 'sous_chef.read'
    template_name = "billing/list.html"

    def get_context_data(self, **kwargs):
        context = super(BillingList, self).get_context_data(**kwargs)
        uf = BillingFilter(self.request.GET, queryset=self.get_queryset())
        context['filter'] = uf

        return context

    def get_queryset(self):
        uf = BillingFilter(self.request.GET)
        return uf.qs.annotate(Count('orders', distinct=True))


class BillingCreate(
        LoginRequiredMixin, PermissionRequiredMixin, generic.CreateView):
    # View to create the billing
    context_object_name = "billing"
    model = Billing
    permission_required = 'sous_chef.edit'

    def get(self, request):
        date = self.request.GET.get('delivery_date', '-')
        date = date if date is not '' else '-'
        year, month = date.split('-')

        if year is '' or month is '':
            messages.add_message(
                self.request, messages.ERROR,
                _("You must select a period to create a billing and click in "
                  "the first step 'Preview'")
            )
            return HttpResponseRedirect(reverse_lazy('billing:add'))

        billing = Billing.objects.billing_create_new(year, month)

        messages.add_message(
            self.request, messages.SUCCESS,
            _("The billing with the identifier #%s "
              "has been successfully created." % billing.id)
        )
        return HttpResponseRedirect(reverse_lazy('billing:list'))


class BillingAdd(
        LoginRequiredMixin, PermissionRequiredMixin, generic.ListView):
    context_object_name = "orders"
    model = Order
    paginate_by = 20
    permission_required = 'sous_chef.edit'
    template_name = "billing/add.html"

    def get_context_data(self, **kwargs):
        context = super(BillingAdd, self).get_context_data(**kwargs)
        uf = DeliveredOrdersByMonth(
            self.request.GET, queryset=self.get_queryset())
        context['filter'] = uf
        text = ''
        count = 0
        for getVariable in self.request.GET:
            if getVariable == "page":
                continue
            for getValue in self.request.GET.getlist(getVariable):
                if count == 0:
                    text += "?" + getVariable + "=" + getValue
                else:
                    text += "&" + getVariable + "=" + getValue
                count += 1

        text = text + "?" if count == 0 else text + "&"
        context['get'] = text

        return context

    def get_queryset(self):
        uf = DeliveredOrdersByMonth(self.request.GET)
        return uf.qs.select_related(
            'client__member'
        ).only(
            'status',
            'delivery_date',
            'client__member__firstname',
            'client__member__lastname'
        ).prefetch_related(Prefetch(
            'orders',
            queryset=Order_item.objects.all().only(
                'order__id',
                'price',
                'billable_flag'
            )
        ))


class BillingSummaryView(
        LoginRequiredMixin, PermissionRequiredMixin, generic.DetailView):
    # Display summary of billing
    model = Billing
    permission_required = 'sous_chef.read'
    template_name = "billing/view.html"
    context_object_name = "billing"
    queryset = Billing.objects.prefetch_related(Prefetch(
        'orders',
        queryset=Order.objects.all().select_related(
            'client__member'
        ).only(
            'client__member__firstname',
            'client__member__lastname',
            'client__rate_type',
            'client__billing_payment_type'
        ).prefetch_related(Prefetch(
            'orders',
            queryset=Order_item.objects.all().only(
                'order__id',
                'price',
                'billable_flag',
                'size',
                'component_group',
                'total_quantity'
            )
        ))
    ))

    def get_template_names(self):
        if self.request.method == "GET" and \
           self.request.GET.get('print'):
            return ['billing/print_summary.html']
        else:
            return super(BillingSummaryView, self).get_template_names()

    def get_context_data(self, **kwargs):
        context = super(BillingSummaryView, self).get_context_data(**kwargs)
        billing = self.object

        # generate a summary
        zero_statistics = {
            'total_main_dishes': {
                'R': 0,
                'L': 0
            },
            'total_billable_sides': 0,
            'total_amount': 0
        }
        # target dict
        summary = copy.deepcopy(zero_statistics)
        summary['payment_types_dict'] = collections.defaultdict(
            lambda: dict(clients=[], **copy.deepcopy(zero_statistics))
        )
        for client, client_summary in billing.summary.items():
            t = client.billing_payment_type
            summary['payment_types_dict'][t]['total_main_dishes']['R'] += (
                client_summary['total_main_dishes']['R']
            )
            summary['payment_types_dict'][t]['total_main_dishes']['L'] += (
                client_summary['total_main_dishes']['L']
            )
            summary['payment_types_dict'][t]['total_billable_sides'] += (
                client_summary['total_billable_sides']
            )
            summary['payment_types_dict'][t]['total_amount'] += (
                client_summary['total_amount']
            )
            summary['payment_types_dict'][t]['clients'].append({
                'id': client.id,
                'firstname': client.member.firstname,
                'lastname': client.member.lastname,
                'payment_type': client.get_billing_payment_type_display() if (
                    client.billing_payment_type is not None) else '',
                'rate_type': client.get_rate_type_display() if (
                    client.rate_type != 'default') else '',
                'total_main_dishes': client_summary['total_main_dishes'],
                'total_billable_sides': client_summary['total_billable_sides'],
                'total_amount': client_summary['total_amount']
            })
            summary['total_main_dishes']['R'] += (
                client_summary['total_main_dishes']['R']
            )
            summary['total_main_dishes']['L'] += (
                client_summary['total_main_dishes']['L']
            )
            summary['total_billable_sides'] += (
                client_summary['total_billable_sides']
            )
            summary['total_amount'] += (
                client_summary['total_amount']
            )

        # sort clients in each payment type group
        for payment_type, statistics in summary['payment_types_dict'].items():
            statistics['clients'].sort(
                key=lambda c: (c['lastname'], c['firstname'])
            )

        # reorder the display for supported & non-supported payment types
        summary['payment_types'] = sorted(
            summary['payment_types_dict'].items(),
            key=lambda tup: {
                ' ': 0,      # 0th position
                'credit': 1,    # 1st position
                'eft': 2,     # 2nd position
                '3rd': 3,  # 3rd position
            }.get(tup[0], 99)  # last position(s)
        )

        context['summary'] = summary

        # Throw a warning if there's any main_dish order with size=None.
        q = Order_item.objects.filter(
            Q(order__in=billing.orders.all()) &
            (Q(size__isnull=True) | Q(size='')) &
            Q(component_group='main_dish')
        )
        if q.exists():
            size_none_orders_info = list(q.values_list(
                'order__id',
                'order__client__member__firstname',
                'order__client__member__lastname'
            ))
            formatted_htmls = ['<ul class="ui list">']
            for i, f, l in size_none_orders_info:
                formatted_htmls.append(
                    '<li><a href="{0}" target="_blank">'
                    '#{1} ({2} {3})'
                    '</a></li>'.format(
                        Order(id=i).get_absolute_url(),
                        i,
                        f,
                        l
                    )
                )
            formatted_htmls.append('</ul>')
            formatted_html = ''.join(formatted_htmls)
            messages.add_message(
                self.request, messages.WARNING,
                string_concat(
                    _('Warning: the order(s) below have not set a "size" '
                      'for main dish and thus have been excluded in '
                      '"Total Main Dishes" column.'),
                    '<br/>',
                    formatted_html
                )
            )
        return context


class BillingOrdersView(
        LoginRequiredMixin, PermissionRequiredMixin, generic.DetailView):
    # Display orders detail of billing
    model = Billing
    permission_required = 'sous_chef.read'
    template_name = "billing/view_orders.html"
    context_object_name = "billing"

src/billing/templates/billing/partials/statistics.html
{% load i18n %}

<div class="ui row">
    <div class="ui small statistic">
      <div class="value">
         <i class="shipping icon" data-content="{% trans 'Delivered orders' %}"></i> {{orders.count}}
      </div>
      <div class="label">
        {% trans 'Delivered orders' %}
      </div>
    </div>
    <div class="ui small statistic">
      <div class="value">
         <i class="dollar icon"></i> {{billing.total_amount}}
      </div>
      <div class="label">
        {% trans 'Revenues' %}
      </div>
    </div>
</div>

src/billing/templates/billing/partials/summary.html
{% load i18n %}
<style>
  {% comment %}define table width/border...{% endcomment %}
  #sc_bs {width:100%;border-collapse:collapse}
  #sc_bs th {text-align:left}
  #sc_bs .border-top {border-top: 1px solid black}
  #sc_bs .border-right {border-right: 1px solid black}
  #sc_bs .center.aligned {text-align:center}
  #sc_bs .right.aligned {text-align:right}
  #sc_bs .top.aligned {vertical-align:top}
  #sc_bs .bottom.aligned {vertical-align:bottom}
  #sc_bs .padding-x {padding-left:1em;padding-right:1em}
  #sc_bs .nowrap {white-space:nowrap}
</style>
<table id="sc_bs">
  <thead>
    <tr class="border-top">
      <th class="bottom aligned">{% trans 'New' as tr_n %}{{ tr_n|upper }}
        <i class="help-text question grey icon link no-print" data-content="{% trans 'Indicates if the client is a new client in this billing period.' %}"></i>
      </th>
      <th class="bottom aligned">{% trans 'Client Name' as tr_cn %}{{ tr_cn|upper }}
        <i class="help-text question grey icon link no-print" data-content="{% trans 'Quickly access the client file.' %}"></i>
      </th>
      <th width="1" class="center aligned bottom aligned padding-x">{% trans 'Payment Method' as tr_pm %}{{ tr_pm|upper }}</th>
      <th width="1" class="center aligned bottom aligned padding-x">{% trans 'Price Scale' as tr_ps %}{{ tr_ps|upper }}</th>
      <th colspan="2" class="center aligned bottom aligned">
        {% trans 'Meals' as tr_m %}{{ tr_m|upper }}
        <i class="help-text question grey icon link no-print" data-content="{% trans 'Number of main dishes in total in this billing period.' %}"></i>
      </th>
      <th class="bottom aligned center aligned">
        {% trans 'Extra' as tr_e %}{{ tr_e|upper }}
        <i class="help-text question grey icon link no-print" data-content="{% trans 'Number of extra side dishes in total in this billing period.' %}"></i>
      </th>
      <th class="right aligned bottom aligned">
        {% trans 'Total' as tr_t %}{{ tr_t|upper }}
        <i class="help-text question grey icon link no-print" data-content="{% trans 'Total amount in this billing period.' %}"></i>
      </th>
      <th class="no-print center aligned bottom aligned">{% trans 'Actions' %}</th>
    </tr>
    <tr class="border-top">
      <th colspan="4"></th>
      <th class="center aligned border-right" style="font-weight:normal">{% trans 'Regular' %}</th>
      <th class="center aligned" style="font-weight:normal">{% trans 'Large' %}</th>
      <th colspan="2"></th>
      <th class="no-print"></th>
    </tr>
  </thead>
  <tbody>
    {% for payment_type, statistics in summary.payment_types %}
      {% for client in statistics.clients %}
    <tr>
      <td>{% comment 'column NEW' %}{% endcomment %}</td>
      <td class="nowrap"><a href="{% url 'member:client_information' pk=client.id %}">{{ client.lastname|upper }}, {{ client.firstname }}</a></td>
      <td class="center aligned nowrap">{{client.payment_type}}</td>
      <td class="center aligned nowrap padding-x">{{client.rate_type}}</td>
      <td class="center aligned border-top border-right">{{client.total_main_dishes.R|default:""}}</td>
      <td class="center aligned border-top">{{client.total_main_dishes.L|default:""}}</td>
      <td class="center aligned border-top">{{client.total_billable_sides|default:""}}</td>
      <td class="right aligned border-top">${{client.total_amount}}</td>
      <td class="no-print center aligned">
        <a class="ui basic icon button" href="{% url 'billing:view_orders' pk=billing.id %}?client={{ client.id }}" title="{% trans 'View orders' %}">
          <i class="icon unhide"></i>
        </a>
      </td>
    </tr>
      {% endfor %}
    <tr>
      <th style="padding-bottom:3em"></th>
      <th colspan="3" class="top aligned nowrap">{% trans 'Subtotal:' as tr_s %}{{ tr_s|upper }}</th>
      <th class="center aligned border-top top aligned">{{statistics.total_main_dishes.R}}</th>
      <th class="center aligned border-top top aligned">{{statistics.total_main_dishes.L}}</th>
      <th class="center aligned border-top top aligned">{{statistics.total_billable_sides}}</th>
      <th class="right aligned border-top top aligned">${{statistics.total_amount}}</th>
      <th class="no-print"></th>
    </tr>
    {% endfor %}

    {% comment 'tfoot' %}to fix Firefox printing issue: FF prints tfoot on every page!{% endcomment %}
    <tr class="border-top">
      <th>{% comment 'column NEW' %}{% endcomment %}</th>
      <th colspan="3" class="nowrap">{% trans "Grand Total:" as gt %}{{ gt|upper }} {{ summary.total_main_dishes.R|add:summary.total_main_dishes.L }}</th>
      <th class="center aligned">{{ summary.total_main_dishes.R }}</th>
      <th class="center aligned">{{ summary.total_main_dishes.L }}</th>
      <th class="center aligned">{{ summary.total_billable_sides }}</th>
      <th class="right aligned">${{ summary.total_amount }}</th>
      <th class="no-print center aligned">
        <a class="ui basic icon button" href="{% url 'billing:view_orders' pk=billing.id %}" title="{% trans 'View orders' %}">
          <i class="icon unhide"></i>
        </a>
      </th>
    </tr>
  </tbody>
</table>