src/meal/urls.py
from django.conf.urls import url

app_name = "meal"
urlpatterns = []

src/member/urls.py
from django.conf.urls import url
from django.utils.translation import ugettext_lazy as _
from django.utils.translation import string_concat

from member.views import (
    ClientWizard,
    ClientDetail,
    ClientList,
    SearchMembers,
    ClientOrderList,
    ClientInfoView,
    ClientPaymentView,
    ClientAllergiesView,
    DeleteRestriction,
    DeleteClientOption,
    DeleteIngredientToAvoid,
    DeleteComponentToAvoid,
    geolocateAddress,
    ClientStatusScheduler,
    ClientStatusSchedulerReschedule,
    ClientStatusView,
    ClientStatusSchedulerDeleteView,
    ClientUpdateBasicInformation,
    ClientUpdateAddressInformation,
    ClientUpdatePaymentInformation,
    ClientUpdateDietaryRestriction,
    ClientUpdateRelationshipsInformation,
    RouteListView,
    RouteDetailView,
    RouteEditView,
    DeliveryHistoryDetailView,
    get_minimised_euclidean_distances_route_sequence,
)

from member.forms import (
    ClientBasicInformation, ClientAddressInformation,
    ClientPaymentInformation, ClientRestrictionsInformation
)
from member.formsets import CreateRelationshipFormset

from note.views import ClientNoteList, ClientNoteListAdd

app_name = "member"

member_forms = ({
    'name':        'basic_information',
    'step_url':    _('basic_information'),
    'create_form': ClientBasicInformation,
    'update_form': ClientUpdateBasicInformation
}, {
    'name':        'address_information',
    'step_url':    _('address_information'),
    'create_form': ClientAddressInformation,
    'update_form': ClientUpdateAddressInformation
}, {
    'name':        'relationships',
    'step_url':    _('relationships'),
    'create_form': CreateRelationshipFormset,
    'update_form': ClientUpdateRelationshipsInformation
}, {
    'name':        'payment_information',
    'step_url':    _('payment_information'),
    'create_form': ClientPaymentInformation,
    'update_form': ClientUpdatePaymentInformation,
}, {
    'name':        'dietary_restriction',
    'step_url':    _('dietary_restriction'),
    'create_form': ClientRestrictionsInformation,
    'update_form': ClientUpdateDietaryRestriction,
})

member_wizard = ClientWizard.as_view(
    list(map(lambda d: (d['name'], d['create_form']), member_forms)),
    i18n_url_names=list(map(
        lambda d: (d['name'], d['step_url']), member_forms
    )),
    url_name='member:member_step'
)


urlpatterns = [
    url(_(r'^create/$'), member_wizard, name='member_step'),
    url(_(r'^create/(?P<step>.+)/$'), member_wizard,
        name='member_step'),
    url(_(r'^list/$'), ClientList.as_view(), name='list'),
    url(_(r'^search/$'), SearchMembers.as_view(), name='search'),
    url(_(r'^view/(?P<pk>\d+)/$'), ClientDetail.as_view(), name='view'),
    url(_(r'^view/(?P<pk>\d+)/orders$'),
        ClientOrderList.as_view(), name='list_orders'),
    url(_(r'^view/(?P<pk>\d+)/information$'),
        ClientInfoView.as_view(), name='client_information'),
    url(_(r'^view/(?P<pk>\d+)/billing$'),
        ClientPaymentView.as_view(), name='client_payment'),
    url(_(r'^view/(?P<pk>\d+)/preferences$'),
        ClientAllergiesView.as_view(), name='client_allergies'),
    url(_(r'^view/(?P<pk>\d+)/notes$'),
        ClientNoteList.as_view(), name='client_notes'),
    url(_(r'^view/(?P<pk>\d+)/notes/add$'),
        ClientNoteListAdd.as_view(), name='client_notes_add'),
    url(_(r'^geolocateAddress/$'), geolocateAddress, name='geolocateAddress'),
    url(_(r'^view/(?P<pk>\d+)/status$'),
        ClientStatusView.as_view(), name='client_status'),
    url(_(r'^client/(?P<pk>\d+)/status/scheduler$'),
        ClientStatusScheduler.as_view(), name='clientStatusScheduler'),
    url(_(r'^client/(?P<pk>\d+)/status/scheduler/reschedule/'
          r'(?P<scheduled_status_1_pk>\d+)'
          r',(?P<scheduled_status_2_pk>\d+)?'
          r'/$'),
        ClientStatusSchedulerReschedule.as_view(),
        name='clientStatusSchedulerReschedule'),
    url(
        r'^status/(?P<pk>\d+)/delete$',
        ClientStatusSchedulerDeleteView.as_view(),
        name='delete_status'
    ),
    url(_(r'^restriction/(?P<pk>\d+)/delete/$'),
        DeleteRestriction.as_view(), name='restriction_delete'),
    url(_(r'^client_option/(?P<pk>\d+)/delete/$'),
        DeleteClientOption.as_view(), name='client_option_delete'),
    url(_(r'^ingredient_to_avoid/(?P<pk>\d+)/delete/$'),
        DeleteIngredientToAvoid.as_view(), name='ingredient_to_avoid_delete'),
    url(_(r'^component_to_avoid/(?P<pk>\d+)/delete/$'),
        DeleteComponentToAvoid.as_view(), name='component_to_avoid_delete'),

    url(_(r'^routes/$'), RouteListView.as_view(), name='route_list'),
    url(_(r'^route/(?P<pk>\d+)/$'),
        RouteDetailView.as_view(), name='route_detail'),
    url(_(r'^route/(?P<pk>\d+)/edit/$'),
        RouteEditView.as_view(), name='route_edit'),
    url(_(r'^route/(?P<pk>\d+)/optimised_sequence/$'),
        get_minimised_euclidean_distances_route_sequence,
        name='route_get_optimised_sequence'),
    url(_(r'^route/(?P<route_pk>\d+)/(?P<date>\d{4}-\d{2}-\d{2})/$'),
        DeliveryHistoryDetailView.as_view(), name='delivery_history_detail'),
]

# Handle client update forms URL
for d in member_forms:
    urlpatterns.append(
        url(string_concat(_(r'^(?P<pk>\d+)/update/'), d['step_url'], '/$'),
            d['update_form'].as_view(),
            name='member_update_' + d['name'])
    )

src/order/urls.py
from django.conf.urls import url
from django.utils.translation import ugettext_lazy as _

from order.views import (
    OrderList,
    OrderDetail,
    CreateOrder,
    CreateOrdersBatch,
    UpdateOrder,
    UpdateOrderStatus,
    CreateDeleteOrderClientBill,
    DeleteOrder)

app_name = "order"

urlpatterns = [
    url(_(r'^list/$'), OrderList.as_view(), name='list'),
    url(_(r'^view/(?P<pk>\d+)/$'), OrderDetail.as_view(), name='view'),
    url(_(r'^create/$'), CreateOrder.as_view(), name='create'),
    # Multiple orders as once
    url(_(r'^create/batch$'),
        CreateOrdersBatch.as_view(), name='create_batch'),

    url(_(r'^update/(?P<pk>\d+)/$'), UpdateOrder.as_view(), name='update'),
    url(
        _(r'^update/(?P<pk>\d+)/status$'),
        UpdateOrderStatus.as_view(),
        name='update_status'
    ),
    url(
        _(r'^update/(?P<pk>\d+)/client_bill$'),
        CreateDeleteOrderClientBill.as_view(),
        name='update_client_bill'
    ),
    url(_(r'^delete/(?P<pk>\d+)/$'), DeleteOrder.as_view(), name='delete'),
]

src/sous_chef/urls.py
from django.conf.urls import include, url
from django.contrib import admin


from page.views import HomeView
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import ugettext_lazy as _

urlpatterns = i18n_patterns(
    url(
        _(r'^admin/'),
        admin.site.urls
    ),
    url(
        _(r'^meal/'),
        include('meal.urls', namespace="meal")
    ),
    url(
        _(r'^member/'),
        include('member.urls', namespace="member")
    ),
    url(
        _(r'^notification/'),
        include('notification.urls', namespace="notification")
    ),
    url(
        _(r'^order/'),
        include('order.urls', namespace="order")
    ),
    url(
        r'^p/',
        include('page.urls', namespace="page")
    ),
    url(r'^$', HomeView.as_view(), name='home'),
    url(
        _(r'^delivery/'),
        include('delivery.urls', namespace="delivery")
    ),
    url(
        _(r'^note/'),
        include('note.urls', namespace="note")
    ),
    url(
        _(r'^billing/'),
        include('billing.urls', namespace="billing")
    ),
    url(
        _(r'^avatar/'),
        include('avatar.urls')
        ),
    prefix_default_language=False
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/member/views.py
# coding: utf-8

import csv

from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseBadRequest
from django.urls import reverse_lazy, reverse
from django.db import transaction
from django.db.models import Q, Prefetch, When, Case, Sum, IntegerField
from django.db.transaction import atomic
from django.http import HttpResponseRedirect, JsonResponse, HttpResponse
from django.shortcuts import get_object_or_404
from django.utils import timezone
from django.utils.decorators import method_decorator, classonlymethod
from django.utils.encoding import force_text
from django.utils.safestring import mark_safe
from django.utils.translation import ugettext_lazy as _
from django.views import generic
from formtools.wizard.views import NamedUrlSessionWizardView

from delivery.views import calculateRoutePointsEuclidean
from meal.models import COMPONENT_GROUP_CHOICES, COMPONENT_GROUP_CHOICES_SIDES
from member.forms import (
    ClientScheduledStatusForm,
    ClientBasicInformation,
    ClientAddressInformation,
    ClientRestrictionsInformation,
    ClientPaymentInformation,
)
from member.formsets import (CreateRelationshipFormset,
                             UpdateRelationshipFormset)
from member.models import (
    Client,
    ClientScheduledStatus,
    Route, DeliveryHistory,
    Member,
    Address,
    Contact,
    Restriction,
    Relationship,
    Client_option,
    ClientFilter,
    ClientScheduledStatusFilter,
    DAYS_OF_WEEK,
    Client_avoid_ingredient,
    Client_avoid_component,
    HOME, WORK, CELL, EMAIL)
from note.models import Note
from order.mixins import FormValidAjaxableResponseMixin
from order.models import SIZE_CHOICES, Order


class NamedUrlSessionWizardView_i18nURL(NamedUrlSessionWizardView):

    @classonlymethod
    def as_view(cls, *args, **kwargs):
        cls.i18n_url_names = kwargs.pop('i18n_url_names')
        return super(NamedUrlSessionWizardView_i18nURL, cls).as_view(
            *args, **kwargs)

    def dispatch(self, request, *args, **kwargs):
        """
        Replace kwargs['step'] as non-i18n step name.
        """
        if 'step' in kwargs:
            i18n_step = kwargs.pop('step')
            try:
                matched_tup = next(
                    tup for tup in self.i18n_url_names
                    if force_text(tup[1]) == i18n_step
                )
                non_i18n_step = matched_tup[0]
            except StopIteration:
                # not found
                non_i18n_step = i18n_step
            finally:
                kwargs['step'] = non_i18n_step
        return super(NamedUrlSessionWizardView_i18nURL, self).dispatch(
            request, *args, **kwargs)

    def get_step_url(self, step):
        """
        Replace non-i18n step name as i18n step name.
        """
        non_i18n_step = step
        try:
            matched_tup = next(
                tup for tup in self.i18n_url_names
                if force_text(tup[0]) == non_i18n_step
            )
            i18n_step = matched_tup[1]
        except StopIteration:
            # not found
            i18n_step = non_i18n_step
        finally:
            return super(NamedUrlSessionWizardView_i18nURL, self).get_step_url(
                i18n_step)


class ClientWizard(
        LoginRequiredMixin, PermissionRequiredMixin,
        NamedUrlSessionWizardView_i18nURL):
    permission_required = 'sous_chef.edit'
    template_name = 'client/create/form.html'

    def get_context_data(self, **kwargs):
        context = super(ClientWizard, self).get_context_data(**kwargs)

        context["weekday"] = DAYS_OF_WEEK
        context["meals"] = list(filter(
            lambda tup: tup[0] != COMPONENT_GROUP_CHOICES_SIDES,
            COMPONENT_GROUP_CHOICES
        ))

        if 'pk' in kwargs:
            context.update({'edit': True})
            context.update({'pk': kwargs['pk']})

        form = context['form']
        if isinstance(form, ClientBasicInformation):
            step_template = 'client/partials/forms/basic_information.html'
        elif isinstance(form, ClientAddressInformation):
            step_template = 'client/partials/forms/address_information.html'
        elif isinstance(form, ClientPaymentInformation):
            step_template = 'client/partials/forms/payment_information.html'
        elif isinstance(form, ClientRestrictionsInformation):
            step_template = 'client/partials/forms/dietary_restriction.html'
        elif isinstance(form, CreateRelationshipFormset):
            step_template = 'client/partials/forms/relationships.html'
        else:
            step_template = None
        context['step_template'] = step_template

        return context

    def get_form_initial(self, step):
        """
        Load initial data.
        """
        initial = {}
        if 'pk' in self.kwargs:
            pk = self.kwargs['pk']
            client = Client.objects.get(id=pk)
            initial = self.load_initial_data(step, client)

        return self.initial_dict.get(step, initial)

    def done(self, form_list, form_dict, **kwargs):
        """
        Process the submitted and validated form data.
        """
        # Use form_dict which allows us to access the wizard’s forms
        # based on their step names.
        pk = None
        self.form_dict = form_dict

        if 'pk' in kwargs:
            pk = kwargs['pk']
        self.save(pk)
        messages.add_message(
            self.request, messages.SUCCESS,
            _("The client has been created")
        )
        return HttpResponseRedirect(reverse_lazy('member:list'))

    def load_initial_data(self, step, client):
        """
        Load initial for the given step and client.
        """
        initial = {
            'firstname': client.member.firstname,
            'lastname': client.member.lastname,
            'alert': client.alert,
            'gender': client.gender,
            'language': client.language,
            'birthdate': client.birthdate,
            'contact_value': client.member.home_phone,
            'street': client.member.address.street,
            'city': client.member.address.city,
            'apartment': client.member.address.apartment,
            'postal_code': client.member.address.postal_code,
            'delivery_note': client.delivery_note,
            'route': client.route,
            'latitude': client.member.address.latitude,
            'longitude': client.member.address.longitude,
            'distance': client.member.address.distance,
            'member': client.id,
            'same_as_client': True,
            'facturation': '',
            'billing_payment_type': '',
        }
        return initial

    def save_json(self, dictonary):
        json = {}

        for days, Days in DAYS_OF_WEEK:
            json['size_{}'.format(days)] = dictonary.get(
                'size_{}'.format(days)
            )

            if json['size_{}'.format(days)] is "":
                json['size_{}'.format(days)] = None

            for meal, Meals in COMPONENT_GROUP_CHOICES:
                if meal is COMPONENT_GROUP_CHOICES_SIDES:
                    continue  # skip "Sides"
                json['{}_{}_quantity'.format(meal, days)] \
                    = dictonary.get(
                    '{}_{}_quantity'.format(meal, days)
                )

        return json

    @atomic
    def save(self, id=None):
        """
        Update or create the member and all its related data.
        """
        basic_information = self.form_dict['basic_information'].cleaned_data
        address_information = self.form_dict[
            'address_information'].cleaned_data
        relationships = self.form_dict[
            'relationships'].cleaned_data
        payment_information = self.form_dict[
            'payment_information'].cleaned_data
        dietary_restriction = self.form_dict[
            'dietary_restriction'].cleaned_data

        member, created = Member.objects.update_or_create(
            id=id,
            defaults={
                'firstname': basic_information.get('firstname'),
                'lastname': basic_information.get('lastname'),
            }
        )

        address, created = Address.objects.update_or_create(
            id=None if member.address is None else member.address.id,
            defaults={
                'street': address_information.get('street'),
                'apartment': address_information.get('apartment'),
                'city': address_information.get('city'),
                'postal_code': address_information.get('postal_code'),
                'latitude': address_information.get('latitude'),
                'longitude': address_information.get('longitude'),
                'distance': address_information.get('distance'),
            }
        )
        member.address = address
        member.save()

        member.add_contact_information(
            HOME, basic_information.get('home_phone')
        )
        member.add_contact_information(
            CELL, basic_information.get('cell_phone')
        )
        member.add_contact_information(
            EMAIL, basic_information.get('email')
        )

        billing_member = self.save_billing_member(member)

        client, created = Client.objects.update_or_create(
            id=member.id,
            defaults={
                'member': member,
                'language': basic_information.get('language'),
                'gender': basic_information.get('gender'),
                'birthdate': basic_information.get('birthdate'),
                'alert': basic_information.get('alert'),
                'rate_type': payment_information.get('facturation'),
                'billing_payment_type':
                    payment_information.get('billing_payment_type'),

src/member/templates/client/base.html
{% extends "base.html" %}
<!-- Load internationalisation utils-->
{% load i18n %}
{% load static %}
{% load rules %}

{% block title %}{% trans "Client" %}{% endblock %}

{% block content %}
{% has_perm 'sous_chef.edit' request.user as can_edit_data %}

<div class="ui secondary pointing fluid menu">

    <h1 class="ui header">
        <div class="content">
            {{client}}
            <div class="sub header">
                {% blocktrans trimmed with created_at=client.member.created_at|date:"d F Y" %}
                  Client since {{ created_at }}
                {% endblocktrans %}
            </div>
        </div>
    </h1>
    <div class="right menu">
      <div class="ui item">
        {% with sc0=client.unprocessed_scheduled_statuses.0 sc1=client.unprocessed_scheduled_statuses.1 %}
        <div class="ui dropdown member status{% if not can_edit_data %} disabled{% endif %}">

          <div class="ui large yellow label text">
            {{ client.get_status_display }}
          </div>

          {% if sc0 %}
          <div class="ui large {% if sc0.needs_attention %}red{% else %}gray{% endif %} label text" {% if sc0.needs_attention %}title="{% trans 'Client status scheduler may not work properly. Please verify.' %}"{% endif %}>
            {% if sc0.needs_attention %}
            <i class="warning sign icon"></i>
            {% endif %}
            {% trans 'Upcoming change' %}
            <div class="detail">
                {{ sc0.get_status_to_display }}
                {% if sc1.get_pair == sc0 %}
                  ({{ sc0.change_date|date:"SHORT_DATE_FORMAT" }}&ndash;{{ sc1.change_date|date:"SHORT_DATE_FORMAT" }})
                {% else %}
                  ({{ sc0.change_date|date:"SHORT_DATE_FORMAT" }})
                {% endif %}
            </div>
          </div>
          {% endif %}
          <i class="dropdown icon"></i>
          <div class="menu">
            {% if not sc0 %}
              {% for k,s in client_status %}
              <div class="item member-update-status" data-url="{% url 'member:clientStatusScheduler' client.id %}?status={{k}}" data-modal-target=".ui.modal.status">
                {{s}}
              </div>
              {% endfor %}
            {% else %}
              <div class="item member-view-upcoming-changes" data-url="{% url 'member:client_status' client.id %}">{% trans 'View upcoming changes' %}</div>
              {% if can_edit_data %}
              <div class="item member-cancel-this-upcoming-change" data-prompt="{% trans 'This cannot be undone. Are you sure?' %}">
                {% trans 'Cancel this upcoming change' %}
                <form style="display:none" action="{% url 'member:delete_status' sc0.id %}" method="post">{% csrf_token %}</form>
              </div>
              <div class="item member-reschedule-this-upcoming-change" data-url="{% if sc1.get_pair != sc0 %}{% url 'member:clientStatusSchedulerReschedule' client.id sc0.pk %}{% else %}{% url 'member:clientStatusSchedulerReschedule' client.id sc0.pk sc1.pk %}{% endif %}" data-modal-target=".ui.modal.status">{% trans 'Reschedule this upcoming change' %}</div>
              {% endif %}
            {% endif %}
          </div>
        </div>
        {% endwith %}
      </div>
    </div>
</div>

<div class="ui modal status"></div>

<div class="sixteen wide column">
    {% include 'client/view/summary.html' %}
</div>

{% if client.alert %}
<div class="sixteen wide column">
    <div class="ui warning message">
        <div class="header">
            {% trans "Important notice" %}
        </div>
        <p>{{ client.alert }}</p>
    </div>
</div>
{% endif %}


<div class="ui stackable relaxed grid container">

    <div class="four wide column">
        {% include 'client/partials/menu.html' %}
    </div>

    <div class="twelve wide column">
        {% block subcontent %}
        <!-- A block used by all children to include content here-->
        {% endblock %}
    </div>

</div>
{% endblock %}

src/member/templates/client/client_info.html
<div class="ui ">
    <div class="ui very relaxed small divided horizontal list">
        <div class="item">
            <i class="large home middle aligned icon"></i>
            <div class="content">
                <a class="header">Address</a>
                <div class="description">{{ client.member.address.street }}</div>
            </div>
        </div>
        <div class="item">
            <i class="large phone middle aligned icon"></i>
            <div class="content">
                <a class="header">Home</a>
                <div class="description">{{client.member.home_phone}}</div>
            </div>
        </div>
        <div class="item">
            <i class="large comment middle aligned icon"></i>
            <div class="content">
                <a class="header">Language</a>
                <div class="description">{{client.get_language_display}}</div>
            </div>
        </div>
        <div class="item">
            <i class="large birthday middle aligned icon"></i>
            <div class="content">
                <a class="header">{{client.birthdate}}</a>
                <div class="description">{{client.age}} years old</div>
            </div>
        </div>
    </div>
</div>

src/member/templates/client/orders_list.html
{% extends "client/base.html" %}
<!-- Load internationalisation utils-->
{% load i18n %}
{% load admin_urls %}

{% block title %}

  {{client}} - Orders list

{% endblock %}

{% block subcontent %}

<div class="ui segment">

    <h2 class="ui header">
        <div class="content">
            {% trans 'Orders' %}
            <div class="sub header">List of all orders from {{client}}.</div>
        </div>
    </h2>
    <div class="ui divider"></div>

    <table class="ui very basic stripped celled table">
        <thead>
            <th class="sorted descending">Order</th>
            <th class="">{% trans 'Delivery Date' %}</th>
            <th class="">{% trans 'Status' %}</th>
            <th class="">{% trans 'Amount' %}</th>
            <th class="">{% trans 'Actions' %}</th>
        </thead>
        <tbody>
            {% for order in orders %}
                <tr>
                    <td><strong>{{order.id}}</strong></td>
                    <td>{{order.delivery_date}}</td>
                    <td>{{order.get_status_display}}</td>
                    <td>${{order.price}}</td>
                    <td>
                        <a class="ui blue icon button"  href="{% url 'order:view' pk=order.id %}"><i class="icon unhide"></i></a>
                        <a class="ui green icon button"  href="{% url 'order:update' pk=order.id %}"><i class="icon edit"></i></a>
                        <a class="ui red icon button order-delete" href="#" data-order-id="{{order.id}}"><i class="icon trash"></i></a>
                    </td>
                </tr>
                {% include "order_confirm_delete.html" %}
            {% endfor %}
        </tbody>

    </table>
 </div>
{% endblock %}

{% block extrajs %}
<script type="text/javascript">
  document.addEventListener( 'DOMContentLoaded', function () {
      $('table').tablesort();
  })

  $('.order-delete').click(function(){
      var order_id = $(this).attr('data-order-id');
      var selector = '.ui.basic.modal.order-' + order_id;
      $(selector).modal('show');
  });
</script>
{% endblock %}