src/delivery/urls.py
from django.conf.urls import url
from django.utils.translation import ugettext_lazy as _

from delivery.views import (Orderlist, MealInformation, RoutesInformation,
                            KitchenCount, MealLabels, DeliveryRouteSheet,
                            RefreshOrderView, CreateDeliveryOfToday,
                            EditDeliveryOfToday)

app_name = "delivery"

urlpatterns = [
    url(_(r'^order/$'), Orderlist.as_view(), name='order'),
    url(_(r'^meal/$'), MealInformation.as_view(), name='meal'),
    url(_(r'^meal/(?P<id>\d+)/$'), MealInformation.as_view(), name='meal_id'),
    url(_(r'^routes/$'), RoutesInformation.as_view(), name='routes'),
    url(_(r'^route/(?P<pk>\d+)/$'),
        EditDeliveryOfToday.as_view(), name='edit_delivery_of_today'),
    url(_(r'^route/(?P<pk>\d+)/create/$'),
        CreateDeliveryOfToday.as_view(), name='create_delivery_of_today'),
    url(_(r'^kitchen_count/$'), KitchenCount.as_view(), name='kitchen_count'),
    url(_(r'^kitchen_count/(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d+)/$'),
        KitchenCount.as_view(), name='kitchen_count_date'),
    url(_(r'^viewDownloadKitchenCount/$'),
        KitchenCount.as_view(), name='downloadKitchenCount'),
    url(_(r'^viewMealLabels/$'), MealLabels.as_view(), name='mealLabels'),
    url(_(r'^route_sheet/(?P<pk>\d+)/$'),
        DeliveryRouteSheet.as_view(), name='route_sheet'),
    url(_(r'^refresh_orders/$'),
        RefreshOrderView.as_view(), name='refresh_orders'),
]

src/meal/urls.py
from django.conf.urls import url

app_name = "meal"
urlpatterns = []

src/member/urls.py
from django.conf.urls import url
from django.utils.translation import ugettext_lazy as _
from django.utils.translation import string_concat

from member.views import (
    ClientWizard,
    ClientDetail,
    ClientList,
    SearchMembers,
    ClientOrderList,
    ClientInfoView,
    ClientPaymentView,
    ClientAllergiesView,
    DeleteRestriction,
    DeleteClientOption,
    DeleteIngredientToAvoid,
    DeleteComponentToAvoid,
    geolocateAddress,
    ClientStatusScheduler,
    ClientStatusSchedulerReschedule,
    ClientStatusView,
    ClientStatusSchedulerDeleteView,
    ClientUpdateBasicInformation,
    ClientUpdateAddressInformation,
    ClientUpdatePaymentInformation,
    ClientUpdateDietaryRestriction,
    ClientUpdateRelationshipsInformation,
    RouteListView,
    RouteDetailView,
    RouteEditView,
    DeliveryHistoryDetailView,
    get_minimised_euclidean_distances_route_sequence,
)

from member.forms import (
    ClientBasicInformation, ClientAddressInformation,
    ClientPaymentInformation, ClientRestrictionsInformation
)
from member.formsets import CreateRelationshipFormset

from note.views import ClientNoteList, ClientNoteListAdd

app_name = "member"

member_forms = ({
    'name':        'basic_information',
    'step_url':    _('basic_information'),
    'create_form': ClientBasicInformation,
    'update_form': ClientUpdateBasicInformation
}, {
    'name':        'address_information',
    'step_url':    _('address_information'),
    'create_form': ClientAddressInformation,
    'update_form': ClientUpdateAddressInformation
}, {
    'name':        'relationships',
    'step_url':    _('relationships'),
    'create_form': CreateRelationshipFormset,
    'update_form': ClientUpdateRelationshipsInformation
}, {
    'name':        'payment_information',
    'step_url':    _('payment_information'),
    'create_form': ClientPaymentInformation,
    'update_form': ClientUpdatePaymentInformation,
}, {
    'name':        'dietary_restriction',
    'step_url':    _('dietary_restriction'),
    'create_form': ClientRestrictionsInformation,
    'update_form': ClientUpdateDietaryRestriction,
})

member_wizard = ClientWizard.as_view(
    list(map(lambda d: (d['name'], d['create_form']), member_forms)),
    i18n_url_names=list(map(
        lambda d: (d['name'], d['step_url']), member_forms
    )),
    url_name='member:member_step'
)


urlpatterns = [
    url(_(r'^create/$'), member_wizard, name='member_step'),
    url(_(r'^create/(?P<step>.+)/$'), member_wizard,
        name='member_step'),
    url(_(r'^list/$'), ClientList.as_view(), name='list'),
    url(_(r'^search/$'), SearchMembers.as_view(), name='search'),
    url(_(r'^view/(?P<pk>\d+)/$'), ClientDetail.as_view(), name='view'),
    url(_(r'^view/(?P<pk>\d+)/orders$'),
        ClientOrderList.as_view(), name='list_orders'),
    url(_(r'^view/(?P<pk>\d+)/information$'),
        ClientInfoView.as_view(), name='client_information'),
    url(_(r'^view/(?P<pk>\d+)/billing$'),
        ClientPaymentView.as_view(), name='client_payment'),
    url(_(r'^view/(?P<pk>\d+)/preferences$'),
        ClientAllergiesView.as_view(), name='client_allergies'),
    url(_(r'^view/(?P<pk>\d+)/notes$'),
        ClientNoteList.as_view(), name='client_notes'),
    url(_(r'^view/(?P<pk>\d+)/notes/add$'),
        ClientNoteListAdd.as_view(), name='client_notes_add'),
    url(_(r'^geolocateAddress/$'), geolocateAddress, name='geolocateAddress'),
    url(_(r'^view/(?P<pk>\d+)/status$'),
        ClientStatusView.as_view(), name='client_status'),
    url(_(r'^client/(?P<pk>\d+)/status/scheduler$'),
        ClientStatusScheduler.as_view(), name='clientStatusScheduler'),
    url(_(r'^client/(?P<pk>\d+)/status/scheduler/reschedule/'
          r'(?P<scheduled_status_1_pk>\d+)'
          r',(?P<scheduled_status_2_pk>\d+)?'
          r'/$'),
        ClientStatusSchedulerReschedule.as_view(),
        name='clientStatusSchedulerReschedule'),
    url(
        r'^status/(?P<pk>\d+)/delete$',
        ClientStatusSchedulerDeleteView.as_view(),
        name='delete_status'
    ),
    url(_(r'^restriction/(?P<pk>\d+)/delete/$'),
        DeleteRestriction.as_view(), name='restriction_delete'),
    url(_(r'^client_option/(?P<pk>\d+)/delete/$'),
        DeleteClientOption.as_view(), name='client_option_delete'),
    url(_(r'^ingredient_to_avoid/(?P<pk>\d+)/delete/$'),
        DeleteIngredientToAvoid.as_view(), name='ingredient_to_avoid_delete'),
    url(_(r'^component_to_avoid/(?P<pk>\d+)/delete/$'),
        DeleteComponentToAvoid.as_view(), name='component_to_avoid_delete'),

    url(_(r'^routes/$'), RouteListView.as_view(), name='route_list'),
    url(_(r'^route/(?P<pk>\d+)/$'),
        RouteDetailView.as_view(), name='route_detail'),
    url(_(r'^route/(?P<pk>\d+)/edit/$'),
        RouteEditView.as_view(), name='route_edit'),
    url(_(r'^route/(?P<pk>\d+)/optimised_sequence/$'),
        get_minimised_euclidean_distances_route_sequence,
        name='route_get_optimised_sequence'),
    url(_(r'^route/(?P<route_pk>\d+)/(?P<date>\d{4}-\d{2}-\d{2})/$'),
        DeliveryHistoryDetailView.as_view(), name='delivery_history_detail'),
]

# Handle client update forms URL
for d in member_forms:
    urlpatterns.append(
        url(string_concat(_(r'^(?P<pk>\d+)/update/'), d['step_url'], '/$'),
            d['update_form'].as_view(),
            name='member_update_' + d['name'])
    )

src/order/urls.py
from django.conf.urls import url
from django.utils.translation import ugettext_lazy as _

from order.views import (
    OrderList,
    OrderDetail,
    CreateOrder,
    CreateOrdersBatch,
    UpdateOrder,
    UpdateOrderStatus,
    CreateDeleteOrderClientBill,
    DeleteOrder)

app_name = "order"

urlpatterns = [
    url(_(r'^list/$'), OrderList.as_view(), name='list'),
    url(_(r'^view/(?P<pk>\d+)/$'), OrderDetail.as_view(), name='view'),
    url(_(r'^create/$'), CreateOrder.as_view(), name='create'),
    # Multiple orders as once
    url(_(r'^create/batch$'),
        CreateOrdersBatch.as_view(), name='create_batch'),

    url(_(r'^update/(?P<pk>\d+)/$'), UpdateOrder.as_view(), name='update'),
    url(
        _(r'^update/(?P<pk>\d+)/status$'),
        UpdateOrderStatus.as_view(),
        name='update_status'
    ),
    url(
        _(r'^update/(?P<pk>\d+)/client_bill$'),
        CreateDeleteOrderClientBill.as_view(),
        name='update_client_bill'
    ),
    url(_(r'^delete/(?P<pk>\d+)/$'), DeleteOrder.as_view(), name='delete'),
]

src/sous_chef/urls.py
from django.conf.urls import include, url
from django.contrib import admin


from page.views import HomeView
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import ugettext_lazy as _

urlpatterns = i18n_patterns(
    url(
        _(r'^admin/'),
        admin.site.urls
    ),
    url(
        _(r'^meal/'),
        include('meal.urls', namespace="meal")
    ),
    url(
        _(r'^member/'),
        include('member.urls', namespace="member")
    ),
    url(
        _(r'^notification/'),
        include('notification.urls', namespace="notification")
    ),
    url(
        _(r'^order/'),
        include('order.urls', namespace="order")
    ),
    url(
        r'^p/',
        include('page.urls', namespace="page")
    ),
    url(r'^$', HomeView.as_view(), name='home'),
    url(
        _(r'^delivery/'),
        include('delivery.urls', namespace="delivery")
    ),
    url(
        _(r'^note/'),
        include('note.urls', namespace="note")
    ),
    url(
        _(r'^billing/'),
        include('billing.urls', namespace="billing")
    ),
    url(
        _(r'^avatar/'),
        include('avatar.urls')
        ),
    prefix_default_language=False
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/delivery/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _

# Create your models here.


class Delivery(models.Model):

    class Meta:
        verbose_name_plural = _('deliveries')

    pass

src/delivery/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _
from django.db.models.functions import Lower

from meal.models import (
    COMPONENT_GROUP_CHOICES_MAIN_DISH, Component, Ingredient)


class DishIngredientsForm(forms.Form):
    maindish = forms.ModelChoiceField(
        label=_("Today's main dish:"),
        queryset=Component.objects.order_by(Lower('name')).filter(
            component_group=COMPONENT_GROUP_CHOICES_MAIN_DISH),
        widget=forms.Select(attrs={'class': 'ui dropdown maindish'}),
    )

    ingredients = forms.ModelMultipleChoiceField(
        label=_('Select main dish ingredients:'),
        queryset=Ingredient.objects.order_by(Lower('name')).all(),
        widget=forms.SelectMultiple(
            attrs={'class': 'ui fluid search dropdown mainingredients'}),
        required=False,
    )

    sides_ingredients = forms.ModelMultipleChoiceField(
        label=_('Select sides ingredients:'),
        queryset=Ingredient.objects.order_by(Lower('name')).all(),
        widget=forms.SelectMultiple(
            attrs={'class': 'ui fluid search dropdown sidesingredients'}),
        required=False,
    )

    def clean_sides_ingredients(self):
        data = self.cleaned_data['sides_ingredients']
        if not data:
            raise forms.ValidationError(
                _("Please choose some Sides ingredients"))
        return data

src/delivery/templates/ingredients.html
{% extends "base.html" %}
<!-- Load Internationalization utils-->
{% load i18n %}
{% load rules %}

{% block title %}{% trans 'Pick Ingredients' %} {% endblock %}

{% block content %}
{% has_perm 'sous_chef.edit' request.user as can_edit_data %}

{% include 'kitchen_count_steps.html' with step='ingredients' %}

<div class="ui secondary pointing fluid menu">
    <h1 class="ui header">{% trans "Pick ingredients" %}</h1>
    <div class="right menu">
        <div class="ui item"><h3><i class="calendar icon"></i>{% now "j F Y" %}</h3></div>
    </div>
</div>

<div class="ui stackable relaxed grid container">

    <div class="sixteen wide column">

        <div class="ui basic segment">
        <div class="ui list">
            <a class="item">
                <i class="food icon"></i>
                <div class="content">
                    <div class="header">{% trans 'Main dish' %}</div>
                    <div class="description">Selecting a main dish in the list will load an editable list of ingredients.</div>
                </div>
            </a>
            <a class="item">
                <i class="refresh icon"></i>
                <div class="content">
                    <div class="header">Restore recipe</div>
                    <div class="description">The <em>Restore recipe</em> action resets the ingredients list to the default one.</div>
                </div>
            </a>
        </div>
        <div class="ui row"></div>
    </div>
</div>
</div>

<form class="ui form" action="{% url 'delivery:meal' %}" method="post">
    <div class="ui stackable relaxed grid container">
        <div class="six wide column">
            {{form.errors}}
            <div class="ui row">
                {% csrf_token %}
                <div class="field dish selection" data-url="{% url 'delivery:meal' %}">
                    <label>{{ form.maindish.label }}</label>
                    {{ form.maindish }}
                </div>
            </div>
        </div>

        <div class="ten wide column">
            <div class="field ingredients selection">
                <label>{{ form.ingredients.label }}</label>
                {{ form.ingredients }}
            </div>
            {% if can_edit_data %}
            <div class="ui row">
                <input class="ui red button restorerecipe {% if not recipe_changed %}disabled{% endif %}" type="submit" value="{% trans "Restore recipe" %}" name="_restore" />
            </div>
            {% endif %}
        </div>

        <div class="ten wide column">
            <div class="field sides_ingredients selection">
                <label>{{ form.sides_ingredients.label }}</label>
                {{ form.sides_ingredients }}
            </div>
        </div>

        {% if can_edit_data %}
        <div class="actions">
          <a class="ui labeled icon big button" href="{% url 'delivery:order' %}">
            <i class="chevron left icon"></i>{% trans "Back" %}
          </a>
          <input class="ui big yellow button confirmingredients {% if not ingredients_changed %}disabled{% endif %}" type="submit" value="{% trans "Confirm all ingredients" %}" name="_update" />
          <a class="ui labeled icon yellow big button nextkitchencount {% if ingredients_changed %}disabled{% endif %}" href="{% url 'delivery:kitchen_count' %}">
            <i class="chevron right icon"></i>{% trans "Next: Print Kitchen Count" %}
          </a>
        </div>
        {% endif %}
    </div>
</form>
{% endblock content %}

src/delivery/templates/kitchen_count.html
{% extends "base.html" %}
<!-- Load Internationalization utils-->
{% load i18n %}
{% load rules %}

{% block title %}{% trans 'Kitchen Count report' %} {% endblock %}

{% block content %}
{% has_perm 'sous_chef.edit' request.user as can_edit_data %}

{% include 'kitchen_count_steps.html' with step='kitchen_count' %}

<div class="ui secondary pointing fluid menu">
    <h1 class="ui header">{% trans "Kitchen Count Report" %}</h1>
    <div class="right menu">
      <div class="ui item"><h3><i class="calendar icon"></i>{% now "j F Y" %}</h3></div>
    </div>
</div>


<div class="ui basic segment no-print">
    {% if num_pages > 0 %}
      <a href="{% url 'delivery:downloadKitchenCount' %}" class="ui labeled icon right pink basic big button" title="{% trans 'Download the kitchen count report' %}">
        <i class="download icon"></i>{% trans "Kitchen Count" %}
      </a>
    {% else %}
      <a href="{% url 'delivery:downloadKitchenCount' %}" class="ui disabled labeled icon right pink basic big button" title="{% trans 'No kitchen count report available' %}">
        <i class="download icon"></i>{% trans "Kitchen Count" %}
      </a>
    {% endif %}
    {% if num_labels > 0 %}
      <a href="{% url 'delivery:mealLabels' %}" class="ui labeled icon right pink basic big button" title="{% trans 'Download the labels' %}">
         <i class="download icon"></i>{% trans "Labels" %}
      </a>
    {% else %}
        <a href="{% url 'delivery:mealLabels' %}" class="ui disabled labeled icon right pink basic big button" title="{% trans 'No labels available' %}">
           <i class="download icon"></i>{% trans "Labels" %}
        </a>
    {% endif %}
</div>


<table class="ui very basic celled table">
  <thead>
   <tr class="top aligned">
    <th class="">{% trans 'Component' %}</th>
    <th class="">{% trans "TOTAL" %}<br>{% trans 'Regular' %}</th>
    <th class="">{% trans "TOTAL" %}<br>{% trans 'Large' %}</th>
    <th class="">{% trans 'Dish today' %}</th>
    <th class="">{% trans 'Ingredients today' %}</th>
   </tr>
  </thead>
  <tbody>
    {% for obj in component_lines %}
      <tr>
        <td><strong>{{obj.component_group}}</strong></td>
        <td>{{obj.rqty}}</td>
        <td>{{obj.lqty}}</td>
        <td>{{obj.name}}</td>
        <td>{{obj.ingredients}}</td>
      </tr>
    {% endfor %}
  </tbody>
</table>

<table class="ui very compact celled structured table">
  <thead>
   <tr class="top center aligned">
    <th class="">{% trans 'Clashing ingredients' %}</th>
    <th class="">{% trans 'Qty' %} - {% trans 'Reg' %}</th>
    <th class="">{% trans 'Qty' %} - {% trans 'Lge' %}</th>
    <th class="">{% trans 'Client' %}</th>
    <th class="">{% trans 'Restrictions' %}</th>
   </tr>
  </thead>
  <tbody>
    {% for obj in meal_lines %}
      <tr{% if obj.client == "" and obj.ingr_clash == "" %} class="active"{% endif %}>
        {% if obj.span == "1" %}
            <td><strong>{{obj.ingr_clash}}</strong></td>
        {% elif obj.span != "-1" %}
              <td rowspan={{obj.span}}>{{obj.ingr_clash}}</td>
        {% endif %}
        {% if obj.client == "SUBTOTAL" %}
            <td class="center aligned"><strong>{{obj.rqty}}</strong></td>
            <td class="center aligned"><strong>{{obj.lqty}}</strong></td>
            <td><strong>{{obj.client}}</strong></td>
        {% else %}
            <td class="center aligned">{{obj.rqty}}</td>
            <td class="center aligned">{{obj.lqty}}</td>
            <td>{{obj.client}}</td>
        {% endif %}
        <td>{{obj.rest_ingr}}{% if obj.rest_ingr %} ; {% endif %} <strong>{{obj.rest_item}}</strong></td>
      </tr>
    {% endfor %}
  </tbody>
</table>

{% if can_edit_data %}
<div class="actions">
    <a class="ui labeled icon big button" href="{% url 'delivery:meal' %}">
        <i class="chevron left icon"></i>{% trans "Back" %}
    </a>
    <a class="ui labeled icon yellow big button" href="{% url 'delivery:routes' %}">
        <i class="chevron right icon"></i>{% trans "Next: Organize Routes" %}
    </a>
</div>
{% endif %}
{% endblock %}

src/delivery/templates/kitchen_count_steps.html
{% load i18n %}

<div class="ui four ordered steps">
  <a class="{% if step == 'orders' %} active{% endif %} step" href="{% url 'delivery:order' %}">
    <div class="content">
      <div class="title">{% trans 'Review Orders' %}</div>
      <div class="description">{% trans 'Review orders for the day.' %}</div>
    </div>
  </a>
  <a class="{% if step == 'ingredients' %} active{% endif %} step" href="{% url 'delivery:meal' %}">
    <div class="content">
      <div class="title">{% trans 'Ingredients' %}</div>
      <div class="description">{% trans 'Pick ingredients for the day.' %}</div>
    </div>
  </a>
  <a class="{% if step == 'kitchen_count' %} active{% endif %} step" href="{% url 'delivery:kitchen_count' %}">
    <div class="content">
      <div class="title">{% trans 'Kitchen Count' %}</div>
      <div class="description">{% trans 'Print the kitchen count.' %}</div>
    </div>
  </a>
  <a class="{% if step == 'routes' %} active{% endif %} step" href="{% url 'delivery:routes' %}">
    <div class="content">
      <div class="title">{% trans 'Routes' %}</div>
      <div class="description">{% trans 'Organize delivery routes.' %}</div>
    </div>
  </a>
</div>

src/delivery/templates/routes.html
{% extends "base.html" %}
<!-- Load Internationalization utils-->
{% load i18n %}
{% load static %}
{% load rules %}

{% block title %}{% trans 'Routes Information' %} {% endblock %}

{% block extrahead %}
    {% load leaflet_tags %}
    {% leaflet_css %}

    <link href="http://netdna.bootstrapcdn.com/font-awesome/4.0.0/css/font-awesome.css" rel="stylesheet">
{% endblock %}

{% block content %}
{% has_perm 'sous_chef.edit' request.user as can_edit_data %}

{% include 'kitchen_count_steps.html' with step='routes' %}

<div class="ui secondary pointing fluid menu">
    <h1 class="ui header">{% trans "Delivery routes" %}</h1>
    <div class="right menu">
      <div class="ui item"><h3><i class="calendar icon"></i>{% now "j F Y" %}</h3></div>
    </div>
</div>

<div class="row">
    <div class="column">
        <a href="?print=yes" class="ui big labeled icon right basic pink button {% if not all_configured %}disabled{% endif %}" title="{% trans 'Download the route sheets report' %}" target="_blank">
            <i class="download icon"></i>{% trans 'Route Sheets' %}
        </a>
        <i class="help-text question pink icon link" data-content="{% trans 'This is activated after organising all deliverable routes.' %}"></i>
    </div>
</div>

<div class="row">
    <div class="sixteen wide column">
      <div class="ui middle aligned divided list">
          {% for route, order_count, has_organised, delivery_history in route_details %}
          <div class="item">
            <div class="right floated content">
              {% if order_count == 0 %}
              {# This route has no orders. No need to display useless buttons. #}
              {% elif has_organised == 'no' %}
              {# The delivery history instance doesn't exist yet. #}
              <form action="{% url 'delivery:create_delivery_of_today' pk=route.pk %}" method="post">
                {% csrf_token %}
                <button class="ui compact labeled icon button" title="{% trans "View, adjust and confirm today's route sequence" %}">
                  <i class="marker icon"></i>{% trans 'Confirm' %}
                </button>
                <a class="ui compact labeled disabled icon button">
                  <i class="list layout icon"></i>{% trans 'Route sheet' %}
                </a>
              </form>
              {% elif has_organised == 'invalid' %}
              {# The client sequence of the delivery history doesn't match the orders. #}
              <a href="{% url 'delivery:edit_delivery_of_today' pk=route.pk %}" class="ui compact labeled red icon button" title="{% trans 'Clients have changed, please reconfirm.' %}">
                  <i class="warning icon"></i>{% trans 'Modified' %}
              </a>
              <a class="ui compact labeled disabled icon button">
                <i class="list layout icon"></i>{% trans 'Route sheet' %}
              </a>
              {% else %}
              {# Configured. #}
              <a href="{% url 'delivery:edit_delivery_of_today' pk=route.pk %}" class="ui compact labeled gray icon button" title="{% trans 'View or edit the organised route' %}">
                  <i class="checkmark icon"></i>{% trans 'Organised' %}
              </a>
              <a href="{% url 'delivery:route_sheet' pk=route.pk %}" class="ui compact labeled icon button" title="{% trans 'Print the route sheet' %}">
                  <i class="list layout icon"></i>{% trans 'Route sheet' %}
              </a>
              {% endif %}
            </div>
            <i class="large location arrow icon"></i>
            <div class="content">
              <div class="header">{{ route.name }}</div>
              <div class="description">
                {% if delivery_history.vehicle == 'cycling' or route.vehicle == 'cycling' %}
                  <i class="bicycle circular icon" title="{% trans 'Cycling' %}"></i>
                {% elif delivery_history.vehicle == 'driving' or route.vehicle == 'driving' %}
                  <i class="car circular icon" title="{% trans 'Driving' %}"></i>
                {% elif delivery_history.vehicle == 'walking' or route.vehicle == 'walking' %}
                  <i class="male circular icon" title="{% trans 'Walking' %}"></i>
                {% endif %}
                  <div class="ui circular pink basic label" title="{% trans 'Number of orders on this route' %}">{{ order_count }}</div>
              </div>
            </div>
          </div>
          {% endfor %}
      </div>
  </div>
</div>

{% if can_edit_data %}
<a class="ui labeled icon big button" href="{% url 'delivery:kitchen_count' %}">
    <i class="chevron left icon"></i>{% trans "Back" %}
</a>
{% endif %}

{% endblock %}

{% block extrajs %}
    {% leaflet_js %}
    {% if debug %}
        <script src="{% static 'js/leaflet.js' %}" type="application/javascript"></script>
    {% else %}
        <script src="{% static 'js/leaflet.min.js' %}" type="application/javascript"></script>
    {% endif %}
{% endblock %}